version: '3.3'
services:
  postgresdb:
    image: postgres:14
    restart: always
    env_file: .env
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: ${POSTGRES_DATA}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-db:${POSTGRES_DATA}
  mongodb:
    image: mongo:latest
    restart: always
    env_file: .env
    container_name: ${MONGODB_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb-db:${MONGODB_DATA}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${RABBIT_CONTAINER_NAME}
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_CLIENT_PORT}:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq/
  keycloak-postgresdb:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgresdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 9001:8080
    command:
      - start-dev
    depends_on:
      - keycloak-postgresdb

volumes:
  postgres-db:
    driver: local
  mongodb-db:
    driver: local
  rabbitmq:
    driver: local
  postgres_data:
    driver: local

